name: aircraft_CUDA_v1
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9.5  # Ensure Python version is compatible with TensorFlow 2.10
  - flask
  - joblib
  - numpy
  - seaborn
  - matplotlib
  - scikit-learn
  - pandas
  - opencv
  - colormap
  - pillow
  - cudatoolkit=11.2  # CUDA 11.2 for TensorFlow 2.10
  - cudnn=8.1  # cuDNN 8.1 is compatible with CUDA 11.2
  - pip
  - pip:
      - tensorflow==2.9.1 # Install TensorFlow 2.10 with GPU support included
      - h5py==3.6.0
      - glob2
