name: aircraft_detection
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - flask
  - joblib
  - tensorflow
  - numpy
  - seaborn
  - matplotlib
  - scikit-learn
  - pandas
  - opencv
  - colormap
  - pillow
  - pip
  - pip:
      - glob2
